apiVersion: v1
kind: Service
metadata:
  namespace: aiplatform
  name: app
  labels:
    service: app
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
    - name: service-port-name 
      port: 80
      protocol: TCP
